version: '2'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "19090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - ./monitoring/prometheus/volume:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - bridge-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/volume:/var/lib/grafana
    restart: always
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge